import = ["/home/nuskad/.config/alacritty/colors.toml", "/home/nuskad/.config/alacritty/fonts.toml"]
live_config_reload = true

[colors]
#background = "#282738"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
dynamic_title = true
#history = 10000
#multiplier = 3
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 82
lines = 24

[window.padding]
x = 30
y = 30
